### ISSUE TITLE
Python not present in official docker images

### ISSUE THREAD

**Issue by labodj** [anudeepND/whitelist#161]
Hi,
after the last update I'm unable to update the whitelist in docker environment using the official PiHole image (https://hub.docker.com/r/pihole/pihole/) since it does not have Python included, is there any workaround?

**Comment by energetictree** [comment]
instead of running inside the docker I actually prefer to running it from the outside, you could modify the pihole location to the location of database outside the docker and modify the subprocess call to run docker exec instead.

For example:
pihole_location = r'/home/pi/.config/appdata/pihole/pihole'
subprocess.call("docker exec -it pihole pihole restartdns reload", shell=True, stdout=subprocess.DEVNULL)

This would be better if it implemented with the parameter instead

**Comment by labodj** [comment]
@energetictree thanks for the hint, I made a PR (https://github.com/anudeepND/whitelist/pull/162)

**Comment by anudeepND** [comment]
@labodj Thanks for the PR. Closing
