### ISSUE TITLE
comm: file 1 is not in sorted order

### ISSUE THREAD

**Issue by pahakalle** [anudeepND/whitelist#74]
The sort part in whitelist.sh's duplicate remove part returns an "error" shown in the image below.

![screenshot 62](https://user-images.githubusercontent.com/1533244/51063252-d91fdb00-1602-11e9-9cce-2b596bf749b2.png)

**Comment by pahakalle** [comment]
Not a breaking error everything seems to still work fine

**Comment by anudeepND** [comment]
@pahakalle Which OS are you using? I tested with a fresh install of Dietpi on my Raspi zero, I did not get this error

**Comment by pahakalle** [comment]
Im using Raspbian

**Comment by anudeepND** [comment]
@pahakalle Can you modify the script from `mv /etc/pihole/whitelist.txt /etc/pihole/whitelist.txt.old && cat /etc/pihole/whitelist.txt.old | sort | uniq >> /etc/pihole/whitelist.txt`

to 

`mv /etc/pihole/whitelist.txt /etc/pihole/whitelist.txt.old && cat /etc/pihole/whitelist.txt.old | sort -n | uniq >> /etc/pihole/whitelist.txt` 

(sort -n instead of sort)

Run the modified script on your system and see if the error is corrected.

https://github.com/anudeepND/whitelist/blob/5b8db95fd139f033d802877be4c8404734c42099/scripts/whitelist.sh#L23

**Comment by anudeepND** [comment]
@pahakalle That's strange, I was unable to reproduce the issue on Raspbian stretch lite (April build)

**Comment by pahakalle** [comment]
I reinstalled the operating system and other stuff and it seemed to fix the issue, whatever it was ¯\_(ツ)_/¯

**Comment by anudeepND** [comment]
@pahakalle If you come across this warning again, try `sort -n` instead of `sort`
