### ISSUE TITLE
philo 

### ISSUE THREAD

**Issue by homerhomer** [anudeepND/whitelist#91]
Hi,  I had to add this to my whitelist to get it to work
api.segment.io

Thanks

**Comment by PoorPocketsMcNewHold** [comment]
[This seems to be a telemetry domain](https://github.com/mattermost/desktop/issues/544), so has the anudeepND whitelist script, or Pi-hole doesn't rely on it to be whitelisted to be working, this surely won't be added. However, if you've forgot which website of service you weren't able to use due to this list being blocked (Even if it's this telemetry service in particular actually), i encourage you to respond it here.

**Comment by anudeepND** [comment]
As @PoorPocketsMcNewHold said, this is a telemetry domain and will not be added to the list.
